version: '2'

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - media_volume:/django-app/media
      - static_volume:/django-app/staticfiles
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - db
      - redis
  redis:
    restart: always
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:14.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - media_volume:/django-app/media
      - static_volume:/django-app/staticfiles

  celery-worker:
    build: 
     context: ./app
    command: celery -A my_delivery worker
    depends_on:
      - server
    env_file:
      - .env
  bot:
    restart: unless-stopped
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - server
    env_file:
      - .env

volumes:
  media_volume: 
  postgres_data: 
  static_volume:
