# Generated by Django 4.2.2 on 2023-06-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_groups_customer_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='customer/avatars', verbose_name='avatar')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_avatar', to='customer.avatars'),
        ),
    ]
