# Generated by Django 4.2.2 on 2023-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_avatars_customer_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatars',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AddField(
            model_name='avatars',
            name='title',
            field=models.CharField(default='qwe', max_length=100, verbose_name='image title'),
        ),
    ]
