# Generated by Django 4.2.2 on 2023-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_avatar_avatars_image_avatars_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='title',
            field=models.CharField(max_length=100, verbose_name='image title'),
        ),
    ]
