# Generated by Django 4.2.2 on 2023-06-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_avatars_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatars',
            options={'verbose_name': 'Avatar'},
        ),
    ]
