# Generated by Django 4.2.2 on 2023-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_favourite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='image',
            field=models.ImageField(upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
    ]
