# Generated by Django 4.2.2 on 2023-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.FloatField(default=1, verbose_name='full price'),
        ),
    ]
