# Generated by Django 4.2.2 on 2023-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_order_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.FloatField(verbose_name='full price'),
        ),
    ]
