# Generated by Django 4.2.2 on 2023-06-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_order_email_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_price',
        ),
    ]
